import type { FieldPath } from "react-hook-form";

import { DEFAULT_CHEMICAL_ACCURACY_HA } from "@/lib/benchmark-presets";
import type { SimulationRunFormData } from "@/types/run";

export const MOLECULE_PAGE_SIZE = 200;

export const initialValues: SimulationRunFormData = {
  molecule_id: null,
  algorithm: null,
  mode: "easy",
  backend_target: null,
  chemical_accuracy_target_ha: DEFAULT_CHEMICAL_ACCURACY_HA,
  backend_options: {
    selection_policy: "manual",
    backend_name: null,
    shots: 4096,
    optimization_level: 1,
    seed_simulator: null,
    seed_transpiler: null,
    aer_method: "automatic",
  },
  noise_profile: null,
  basis_set_override: "",
  easy_options: {
    goal: "balanced",
  },
  advanced_vqe: {
    ansatz_name: "NumberPreserving",
    optimizer_name: "COBYLA",
    max_iterations: 448,
    max_function_evaluations: 448,
    reps: 2,
    initial_point_strategy: "zero_plus_seeded_random",
    initial_point_candidates: 2,
    optimizer_options_text: "",
    initial_parameters_text: "",
    parameter_bounds_text: "",
    seed: null,
    convergence_threshold: null,
  },
  advanced_sqd: {
    samples_per_batch: 512,
    num_batches: 8,
    max_iterations: 8,
    sampling_state_source: "vqe",
    sampling_vqe_ansatz_name: "NumberPreserving",
    sampling_vqe_optimizer_name: "COBYLA",
    sampling_vqe_max_iterations: 448,
    sampling_vqe_reps: 2,
    sampling_vqe_seed: null,
    num_elec_a: null,
    num_elec_b: null,
    energy_tol: 7.5e-5,
    occupancies_tol: 7.5e-5,
    min_selected_configurations: 2,
    seed: null,
    symmetrize_spin: false,
    carryover_threshold: null,
    max_dim_mode: "shared",
    max_dim: 32,
    max_dim_a: null,
    max_dim_b: null,
    spin_sq_target: null,
    sci_solver_options_text: "",
  },
  advanced_kqd: {
    krylov_dim: 8,
    time_step: 0.35,
    evolution_method: "exact",
    trotter_steps: 1,
    residual_tolerance: 1e-8,
  },
  advanced_qfd: {
    num_time_points: 8,
    max_time: 2.5,
    time_grid_type: "linear",
    trotter_steps: 1,
    residual_tolerance: 1e-6,
  },
  advanced_qse: {
    reference_method: "hf",
    provided_state_vector_text: "[1, 0]",
    provided_sector_rows: [{ bitstring: "", real: "1", imag: "0" }],
    excitation_level: "singles_doubles",
    max_subspace_dim: 8,
    vqe_reference_ansatz_name: "NumberPreserving",
    vqe_reference_optimizer_name: "COBYLA",
    vqe_reference_max_iterations: 256,
    vqe_reference_reps: 1,
    regularization: 1e-7,
    overlap_threshold: 1e-5,
    residual_tolerance: 1e-8,
  },
  advanced_skqd: {
    num_elec_a: null,
    num_elec_b: null,
    min_selected_configurations: 2,
    seed: null,
    symmetrize_spin: false,
    max_dim_mode: "shared",
    max_dim: 32,
    max_dim_a: null,
    max_dim_b: null,
    spin_sq_target: null,
    sci_solver_options_text: "",
    samples_per_state: 1024,
    krylov_extension_dim: 4,
    time_step: 0.22,
    residual_tolerance: 1e-6,
  },
};

export const allRunFormFields: FieldPath<SimulationRunFormData>[] = [
  "molecule_id",
  "algorithm",
  "mode",
  "backend_target",
  "chemical_accuracy_target_ha",
  "backend_options.selection_policy",
  "backend_options.backend_name",
  "backend_options.shots",
  "backend_options.optimization_level",
  "backend_options.seed_simulator",
  "backend_options.seed_transpiler",
  "backend_options.aer_method",
  "noise_profile",
  "easy_options.goal",
  "advanced_vqe.ansatz_name",
  "advanced_vqe.optimizer_name",
  "advanced_vqe.max_iterations",
  "advanced_vqe.max_function_evaluations",
  "advanced_vqe.reps",
  "advanced_vqe.initial_point_strategy",
  "advanced_vqe.initial_point_candidates",
  "advanced_vqe.optimizer_options_text",
  "advanced_vqe.initial_parameters_text",
  "advanced_vqe.parameter_bounds_text",
  "advanced_vqe.seed",
  "advanced_vqe.convergence_threshold",
  "advanced_sqd.samples_per_batch",
  "advanced_sqd.num_batches",
  "advanced_sqd.max_iterations",
  "advanced_sqd.sampling_state_source",
  "advanced_sqd.sampling_vqe_ansatz_name",
  "advanced_sqd.sampling_vqe_optimizer_name",
  "advanced_sqd.sampling_vqe_max_iterations",
  "advanced_sqd.sampling_vqe_reps",
  "advanced_sqd.sampling_vqe_seed",
  "advanced_sqd.num_elec_a",
  "advanced_sqd.num_elec_b",
  "advanced_sqd.energy_tol",
  "advanced_sqd.occupancies_tol",
  "advanced_sqd.min_selected_configurations",
  "advanced_sqd.seed",
  "advanced_sqd.symmetrize_spin",
  "advanced_sqd.carryover_threshold",
  "advanced_sqd.max_dim_mode",
  "advanced_sqd.max_dim",
  "advanced_sqd.max_dim_a",
  "advanced_sqd.max_dim_b",
  "advanced_sqd.spin_sq_target",
  "advanced_sqd.sci_solver_options_text",
  "advanced_kqd.krylov_dim",
  "advanced_kqd.time_step",
  "advanced_kqd.evolution_method",
  "advanced_kqd.trotter_steps",
  "advanced_kqd.residual_tolerance",
  "advanced_qfd.num_time_points",
  "advanced_qfd.max_time",
  "advanced_qfd.time_grid_type",
  "advanced_qfd.trotter_steps",
  "advanced_qfd.residual_tolerance",
  "advanced_qse.reference_method",
  "advanced_qse.provided_state_vector_text",
  "advanced_qse.excitation_level",
  "advanced_qse.max_subspace_dim",
  "advanced_qse.vqe_reference_ansatz_name",
  "advanced_qse.vqe_reference_optimizer_name",
  "advanced_qse.vqe_reference_max_iterations",
  "advanced_qse.vqe_reference_reps",
  "advanced_qse.regularization",
  "advanced_qse.overlap_threshold",
  "advanced_qse.residual_tolerance",
  "advanced_skqd.samples_per_state",
  "advanced_skqd.num_elec_a",
  "advanced_skqd.num_elec_b",
  "advanced_skqd.min_selected_configurations",
  "advanced_skqd.seed",
  "advanced_skqd.symmetrize_spin",
  "advanced_skqd.max_dim_mode",
  "advanced_skqd.max_dim",
  "advanced_skqd.max_dim_a",
  "advanced_skqd.max_dim_b",
  "advanced_skqd.spin_sq_target",
  "advanced_skqd.sci_solver_options_text",
  "advanced_skqd.krylov_extension_dim",
  "advanced_skqd.time_step",
  "advanced_skqd.residual_tolerance",
];
